#### general settings
name: ESRGANx4_blacked_for_adrianna
use_tb_logger: true
model: srgan
distortion: sr
scale: 4
gpu_ids: [0]
amp_opt_level: O1

#### datasets
datasets:
  train:
    name: vixen
    mode: LQGT
    dataroot_GT: K:\4k6k\vixen4k\hr
    dataroot_LQ: E:\4k6k\mmsr\results\RRDB_ESRGAN_x4\vixen
    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 12
    target_size: 256
    use_flip: false
    use_rot: false
    color: RGB
  val:
    name: adrianna_val
    mode: LQGT
    dataroot_GT: ../datasets/adrianna/val/hr
    dataroot_LQ: ../datasets/adrianna/val/lr

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 64

#### path
path:
  pretrain_model_G: ../experiments/ESRGANx4_blacked_for_adrianna/models/15500_G.pth
  pretrain_model_D: ../experiments/ESRGANx4_blacked_for_adrianna/models/15500_D.pth
  resume_state: ../experiments/ESRGANx4_blacked_for_adrianna/training_state/15500.state
  strict_load: true

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [10000, 20000, 30000, 40000, 50000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: !!float 1e0
  feature_weight_decay: 1
  feature_weight_decay_steps: 2500
  feature_weight_minimum: !!float 1e-3
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 1e-1

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e2

#### logger
logger:
  print_freq: 50
  save_checkpoint_freq: !!float 5e2
