#### general settings
name: ESRGAN_adrianna_corrupt_finetune
use_tb_logger: true
model: corruptgan
distortion: downsample
scale: 4
gpu_ids: [0]
amp_opt_level: O1

#### datasets
datasets:
  train:
    name: blacked
    mode: downsample
    dataroot_GT: ../datasets/blacked/train/hr
    dataroot_LQ: ../datasets/adrianna/train/lr
    mismatched_Data_OK: true
    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 16
    target_size: 64
    use_flip: false
    use_rot: false
    color: RGB
  val:
    name: blacked_val
    mode: downsample
    target_size: 64
    dataroot_GT: ../datasets/blacked/val/hr
    dataroot_LQ: ../datasets/blacked/val/lr

#### network structures
network_G:
  which_model_G: HighToLowResNet
  in_nc: 3
  out_nc: 3
  nf: 128
  nb: 30
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 96

#### path
path:
  pretrain_model_G: ../experiments/blacked_lqprn_corrupt_G.pth
  pretrain_model_D: ../experiments/blacked_lqprn_corrupt_D.pth
  resume_state: ~
  strict_load: true

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-5
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-5
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [1000, 2000, 3000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 0
  gan_type: gan  # gan | ragan
  gan_weight: !!float 1e-1

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e2

#### logger
logger:
  print_freq: 50
  save_checkpoint_freq: !!float 5e2
