#### general settings
name: downsample_GAN_blacked
use_tb_logger: true
model: srgan
distortion: sr
scale: .25
gpu_ids: [0]
amp_opt_level: O1

#### datasets
datasets:
  train:
    name: blacked
    mode: GTLQ
    dataroot_GT: ../datasets/blacked/train/hr
    dataroot_LQ: ../datasets/lqprn/train/lr

    use_shuffle: true
    n_workers: 0  # per GPU
    batch_size: 7
    target_size: 64
    use_flip: false
    use_rot: false
    color: RGB
  val:
    name: blacked_val
    mode: LQGT
    dataroot_GT: ../datasets/vrp/validation/hr
    dataroot_LQ: ../datasets/vrp/validation/lr

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 64

#### path
path:
  #pretrain_model_G: ../experiments/blacked_gen_20000_epochs.pth
  #pretrain_model_D: ../experiments/blacked_disc_20000_epochs.pth
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [10000, 30000, 50000, 70000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_weight: 0
  gan_type: ragan  # gan | ragan
  gan_weight: 1

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e2

#### logger
logger:
  print_freq: 50
  save_checkpoint_freq: !!float 5e2
