#### general settings
name: resgen_movies
use_tb_logger: true
model: srgan
distortion: sr
scale: 4
gpu_ids: [0]
amp_opt_level: O1

#### datasets
datasets:
  train:
    name: movies
    mode: LQGT
    dataroot_GT: F:\\upsample_reg\\for_training\\hr
    dataroot_LQ: F:\\upsample_reg\\for_training\\lr_corrupted
    doCrop: false
    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 8
    target_size: 256
    color: RGB
  val:
    name: movies_val
    mode: LQGT
    dataroot_GT: F:\\upsample_reg\\for_training\\val\\hr
    dataroot_LQ: F:\\upsample_reg\\for_training\\val\\lr

#### network structures
network_G:
  which_model_G: ResGenV2
  nf: 256
  nb_denoiser: 20
  nb_upsampler: 10
network_D:
  which_model_D: discriminator_resnet_passthrough
  nf: 64

#### path
path:
  #pretrain_model_G: ~
  #pretrain_model_D: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 6e-5
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 6e-5
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [20000, 60000, 80000, 100000]
  lr_gamma: 0.5
  mega_batch_factor: 1

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  feature_weight_decay: 1
  feature_weight_decay_steps: 1
  feature_weight_minimum: 1
  gan_type: gan  # gan | ragan
  gan_weight: !!float 1e-2

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e2

#### logger
logger:
  print_freq: 50
  save_checkpoint_freq: !!float 5e2
