#### general settings
name: corruptGAN_4k_lqprn_closeup_hq_to_hq
use_tb_logger: true
model: corruptgan
distortion: downsample
scale: 1
gpu_ids: [0]
amp_opt_level: O1

#### datasets
datasets:
  train:
    name: blacked
    mode: downsample
    dataroot_GT: K:\\4k6k\\4k_closeup\\hr
    dataroot_LQ: E:\\4k6k\\adrianna\\for_training\\hr
    mismatched_Data_OK: true
    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 16
    target_size: 256
    use_flip: false
    use_rot: false
    color: RGB
  val:
    name: blacked_val
    mode: downsample
    target_size: 256
    dataroot_GT: ../datasets/blacked/val/hr
    dataroot_LQ: ../datasets/blacked/val/hr

#### network structures
network_G:
  which_model_G: HighToLowResNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 56
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 128

#### path
path:
  pretrain_model_G: ~
  resume_state: ~
  strict_load: true

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [4000, 8000, 12000, 15000, 20000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 0
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 1e-1

  D_update_ratio: 2
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e2

#### logger
logger:
  print_freq: 50
  save_checkpoint_freq: !!float 5e2
