#### general settings
name: blacked_fix_and_upconv_xl
use_tb_logger: true
model: srgan
distortion: sr
scale: 4
gpu_ids: [0]
amp_opt_level: O1

#### datasets
datasets:
  train:
    name: vixcloseup
    mode: LQGT
    dataroot_GT: K:\4k6k\4k_closeup\hr
    dataroot_LQ: K:\4k6k\4k_closeup\lr_corrupted
    doCrop: false
    use_shuffle: true
    n_workers: 12  # per GPU
    batch_size: 24
    target_size: 256
    color: RGB
  val:
    name: adrianna_val
    mode: LQGT
    dataroot_GT: E:\4k6k\datasets\adrianna\val\hhq
    dataroot_LQ: E:\4k6k\datasets\adrianna\val\hr

#### network structures
network_G:
  which_model_G: RRDBNetXL
  in_nc: 3
  out_nc: 3
  nf: 64
  nblo: 18
  nbmed: 8
  nbhi: 6
network_D:
  which_model_D: discriminator_resnet_passthrough
  in_nc: 3
  nf: 42

#### path
path:
  #pretrain_model_G: ../experiments/blacked_fix_and_upconv_xl_part1/models/3000_G.pth
  #pretrain_model_D: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 4e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [20000, 40000, 50000, 60000]
  lr_gamma: 0.5
  mega_batch_factor: 3

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  feature_weight_decay: 1
  feature_weight_decay_steps: 500
  feature_weight_minimum: 1
  gan_type: gan  # gan | ragan
  gan_weight: !!float 1e-2

  D_update_ratio: 1
  D_init_iters: -1

  manual_seed: 10
  val_freq: !!float 5e2

#### logger
logger:
  print_freq: 50
  save_checkpoint_freq: !!float 5e2
